/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Binance WebSocket 24-hour asset payload ticker */
        TickerResponse: {
            /** @description Event type */
            e: string;
            /**
             * Format: int64
             * @description Event time in milliseconds
             */
            E: number;
            /** @description Symbol (trading pair) */
            s: string;
            /** @description Price change in 24h */
            p: string;
            /** @description Price change percent in 24h */
            P: string;
            /** @description Weighted average price */
            w?: string;
            /** @description First trade price before the 24h rolling window */
            x?: string;
            /** @description Last price */
            c: string;
            /** @description Last trade quantity */
            Q?: string;
            /** @description Best bid price */
            b?: string;
            /** @description Best bid quantity */
            B?: string;
            /** @description Best ask price */
            a?: string;
            /** @description Best ask quantity */
            A?: string;
            /** @description Open price 24h ago */
            o?: string;
            /** @description High price in 24h */
            h?: string;
            /** @description Low price in 24h */
            l?: string;
            /** @description Total traded base asset volume */
            v?: string;
            /** @description Total traded quote asset volume */
            q?: string;
            /**
             * Format: int64
             * @description Statistics open time in milliseconds
             */
            O?: number;
            /**
             * Format: int64
             * @description Statistics close time in milliseconds
             */
            C?: number;
            /**
             * Format: int64
             * @description First trade ID
             */
            F?: number;
            /**
             * Format: int64
             * @description Last trade ID
             */
            L?: number;
            /** @description Total number of trades */
            n?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
